// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// C_normCentroidMz
List C_normCentroidMz(SEXP mz_vector, SEXP mz_upperLimit_vector);
RcppExport SEXP _mzDataTable_C_normCentroidMz(SEXP mz_vectorSEXP, SEXP mz_upperLimit_vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mz_vector(mz_vectorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mz_upperLimit_vector(mz_upperLimit_vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(C_normCentroidMz(mz_vector, mz_upperLimit_vector));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mzDataTable_C_normCentroidMz", (DL_FUNC) &_mzDataTable_C_normCentroidMz, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_mzDataTable(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
