# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp function for normCentroidMz
#' SEXP
#' @param mz_vector A sorted numeric vecotor
#' @param mz_upperLimit_vector the mz_vector multiplied by ppmTol*(10^(-6)) and added to mz
#'
#' @export
C_normCentroidMz <- function(mz_vector, mz_upperLimit_vector) {
    .Call(`_mzDataTable_C_normCentroidMz`, mz_vector, mz_upperLimit_vector)
}

